import json
import os

def build():
    cwd = os.path.dirname(os.path.abspath(__file__))
    index_path = os.path.join(cwd, "index.html")
    css_path = os.path.join(cwd, "index.css")
    js_path = os.path.join(cwd, "app.js")
    data_path = os.path.join(cwd, "parsed_inventory_enriched.json")
    data_cache_path = os.path.join(cwd, "DataCache.js")
    out_path = os.path.join(cwd, "index_gas.html")

    print("Building Google Apps Script deployment file...")

    if not os.path.exists(index_path):
        print(f"Error: {index_path} not found.")
        return
    if not os.path.exists(css_path):
        print(f"Error: {css_path} not found.")
        return
    if not os.path.exists(js_path):
        print(f"Error: {js_path} not found.")
        return
    if not os.path.exists(data_path):
        print(f"Error: {data_path} not found.")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        html_content = f.read()

    with open(css_path, "r", encoding="utf-8") as f:
        css_content = f.read()

    with open(js_path, "r", encoding="utf-8") as f:
        js_content = f.read()

    with open(data_path, "r", encoding="utf-8") as f:
        parsed_inventory = json.load(f)

    inventory_json = json.dumps(parsed_inventory, ensure_ascii=False, separators=(",", ":"))
    chunks = [inventory_json[i:i + 50000] for i in range(0, len(inventory_json), 50000)]
    cache_js = [
        "// Auto-generated by build_gas.py. Do not edit manually.",
        "var EMBEDDED_INVENTORY_CHUNKS = [",
    ]
    cache_js.extend("  " + json.dumps(chunk, ensure_ascii=False) + "," for chunk in chunks)
    cache_js.extend([
        "];",
        "function getEmbeddedInventoryData_() {",
        "  return EMBEDDED_INVENTORY_CHUNKS.join('');",
        "}",
        "",
    ])
    with open(data_cache_path, "w", encoding="utf-8") as f:
        f.write("\n".join(cache_js))
    print(f"Generated DataCache.js with {len(chunks)} chunks.")

    # Replace CSS link
    css_link = '<link rel="stylesheet" href="index.css">'
    css_embedded = f"<style>\n{css_content}\n</style>"
    if css_link in html_content:
        html_content = html_content.replace(css_link, css_embedded)
        print("Embedded index.css successfully.")
    else:
        print("Warning: CSS link not found in index.html, searching alternative...")
        # Fallback if there are spaces/attributes variations
        import re
        html_content, count = re.subn(r'<link\s+[^>]*href=["\']index\.css["\'][^>]*>', css_embedded, html_content)
        if count > 0:
            print(f"Embedded index.css successfully (regex matched {count} times).")
        else:
            print("Error: Could not embed index.css.")

    # GAS boot config must be available before app.js registers/runs initialization.
    preload_scriptlet = """    <!-- GAS 啟動設定：入口頁不內嵌大型資料，避免 iframe 解析卡住 -->
    <script>
    (function(){
      try { window.__SCRIPT_URL__ = <?!= JSON.stringify(scriptUrl || '') ?>; } catch(e) { window.__SCRIPT_URL__ = ''; }
      window.__PRELOADED_INVENTORY__ = null;
    })();
    </script>"""

    # Replace JS script tag
    js_tag = '<script src="app.js"></script>'
    js_embedded = f"{preload_scriptlet}\n<script>\n{js_content}\n</script>"
    if js_tag in html_content:
        html_content = html_content.replace(js_tag, js_embedded)
        print("Embedded app.js successfully.")
    else:
        print("Warning: JS script tag not found in index.html, searching alternative...")
        import re
        html_content, count = re.subn(r'<script\s+[^>]*src=["\']app\.js["\'][^>]*>\s*</script>', js_embedded, html_content)
        if count > 0:
            print(f"Embedded app.js successfully (regex matched {count} times).")
        else:
            print("Error: Could not embed app.js.")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(f"Build complete. Compiled single page saved to: {out_path}")

if __name__ == "__main__":
    build()
